config/routes.rb
Rails.application.routes.draw do

  resources :pins do
    collection do 
      get "your_pins"
      get "user_pins"
    end
  end

  devise_for :users

  root 'pages#index'

  

end

app/models/board.rb
class Board < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :boards

	has_attached_file :image, styles: { index: "318x180>", show: "636x360>" } , default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates :image, attachment_presence: true
	validates :title, presence: true
	validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :name, presence: true
	validates :username, presence: true

	has_many :pins
	has_many :boards
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	 protected

	  # def after_sign_in_path_for resource_or_scope
	  #   blog_posts_path
	  # end

	 def after_sign_out_path_for resource_or_scope
	    root_path
	end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
      :password_confirmation, :name, :username) }

     devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
     :password_confirmation, :current_password, :name, :username) }
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	

	def index
		@pins = Pin.all
	end

	def show
		@pin = Pin.find(params[:id])
	end

	def new
		@pin = Pin.new
	end

	def edit
		@pin = Pin.find(params[:id])
	end

	def create
		@pin = Pin.new(pin_params)
		@pin.update_attribute("user", current_user)
		@pin.save
		render :show
	end

	def update
		respond_to do |format|
	      	if @pin.update(pin_params)
	      		format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
				format.json { render :show, status: :ok, location: @pin }
	      	else
	        		format.html { render :edit }
	        		format.json { render json: @pin.errors, status: :unprocessable_entity }
	      	end
	    	end
	end

	def destroy
		@pin = Pin.find(params[:id])
		@pin.destroy
		respond_to do |format|
			format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def your_pins
	end

	def user_pins
		@user = User.find(params[:id])
	end

end


private



	def pin_params
		params.require(:pin).permit(:image, :title, :description)
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Pinterest</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
  
	</head>
	<body>

		<nav class="navbar navbar-light bg-faded">
		  <a class="navbar-brand" href="#">
		  	<% if user_signed_in? %>
		  		<%= current_user.name %></a>
		  		<% else %>
		  		Log in below to get started
		  	<% end %>
		  <ul class="nav navbar-nav">
		    <li class="nav-item active">
		      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="#">Link 2</a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="#">Link 3</a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="#">Link 4</a>
		    </li>
		  </ul>
		  <img src="https://upload.wikimedia.org/wikipedia/commons/9/94/Pinterest_logo.png" height="30px" width="520px" style="margin-left: 30px;">
		  <form class="form-inline pull-xs-right">
		    <input class="form-control" type="text" placeholder="Search">
		    <button class="btn btn-success-outline" type="submit">Search</button>
		  </form>
		</nav>

	<%= yield %>

	</body>
</html>

app/views/pages/index.html.erb
<h1>Hi! Welcome to Pinterest</h1><br>
	<% if user_signed_in? %>
	                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
	                <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-success" %>
	                <%= link_to "Create a new pin", new_pin_path, class: "btn btn-warning" %>
	              <%  else %>
	                <%= link_to "Sign in", new_user_session_path, class: "btn btn-info" %>
	                <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
	            <% end %>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <%= f.file_field :image %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :username, value: current_user.username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/_pins.html.erb
<div class="container-fluid">
  <div class="card-deck-wrapper">
    <div class="card-columns">
      <% @pins.each do |pin| %>
        <div class="card">
          <%= image_tag pin.image.url(:index), class: 'card-img-top' %>
          <div class="card-block">
            <h4><%= pin.title %></h4>
            <p><%= pin.description %></p>
            <%= link_to 'Show', pin_path(pin), class: "btn btn-primary btn-sm" %>
            <% if current_user == pin.user %>
              <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-info btn-sm" %>
              <%= link_to 'Delete', pin_path(pin), method: :delete, class: "btn btn-danger btn-sm"%>
            <% end %>
          </div>
        </div>
     <% end %>
   </div>
  </div>
</div>

app/views/pins/edit.html.erb
<h1>Edit a pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="container">
	<%= render "pins" %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<h1 id="notice"><strong>Pins</strong><%= notice %></h1><br>

<div class="container">
		<div class="card-deck-wrapper">
		  <div class="card-deck">
		    <div class="card">
		    	<%= image_tag @pin.image.url(:index), class: "card-img-top" %>
		      <div class="card-block">
		        <h4 class="card-title"><%= @pin.title %></h4>
		        <p class="card-text"><%= @pin.description %></p>
		        <p class="card-text"><small class="text-muted">Pinned at: <%= local_time(@pin.created_at) %></small></p>
		      </div>
		    </div>
		</div>

		<br><p><%= link_to 'Edit', edit_pin_path(@pin) %></p>
		<br><p><%= link_to 'Back', pins_path(@pin) %></p>
</div>

app/views/pins/user_pins.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header text-center">
  <h1><%= @user.username %>'s pins</h1>
</div>

<div class='container'>
  <% @user.pins.each do |pin| %>
    <div class="well">
      <h3><%= link_to pin.title, pin %></h3>
      <p>author: <%= pin.user.username %></p>
      <p>published: <%= local_time(pin.created_at) %></p>
    </div>
  <% end %>
</div>
<br>

app/views/pins/your_pins.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header text-center">
  <h1>Your Pins</h1>
</div>

<div class='container'>
  <% current_user.pins.each do |pin| %>
    <div class="well well-lg">
      <h3><%= link_to pin.title, pin %></h3>
      <p>author: <%= pin.user.username %></p>
      <p>published: <%= local_time(pin.created_at) %></p>
      <%= link_to 'Edit', edit_pin_path(pin) %>
      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'New Pin', new_pin_path %>